SELECT priority, item_no, table_name, object_type, object_name, status, note
FROM (
  SELECT et.priority, et.item_no, et.table_name, 'TABLE' AS object_type, et.table_name AS object_name,
         'missing' AS status, et.note
  FROM (
    SELECT 'P1' priority, 'P1-001' item_no, 'drh_h5_order' table_name, 'core' note
    UNION ALL SELECT 'P1','P1-002','drh_live_user','core; includes app_phone_*'
    UNION ALL SELECT 'P1','P1-003','drh_applet_user','core'
    UNION ALL SELECT 'P1','P1-004','drh_book_question_record','core'
    UNION ALL SELECT 'P1','P1-005','drh_external_book_question_record','core'
    UNION ALL SELECT 'P1','P1-006','drh_book_edit_address_compensation','core'
    UNION ALL SELECT 'P1','P1-007','drh_real_address_record','core'
    UNION ALL SELECT 'P1','P1-008','app_study_info','p1'
    UNION ALL SELECT 'P1','P1-009','drh_app_white','p1'
    UNION ALL SELECT 'P1','P1-010','drh_applet_black_phone','p1'
    UNION ALL SELECT 'P1','P1-011','drh_applet_player','p1'
    UNION ALL SELECT 'P1','P1-012','drh_gx_channel','p1'
    UNION ALL SELECT 'P1','P1-013','drh_leads_noqw_send_msg_task_detail','p1'
    UNION ALL SELECT 'P1','P1-014','drh_live_works_user','p1'
    UNION ALL SELECT 'P1','P1-015','drh_renew_data','p1'
    UNION ALL SELECT 'P1','P1-016','drh_sms_trigger_user','p1'
    UNION ALL SELECT 'P1','P1-017','drh_specail_user','p1'
    UNION ALL SELECT 'P1','P1-018','drh_sph_supplier_info','p1'
    UNION ALL SELECT 'P1','P1-019','drh_user','p1'
    UNION ALL SELECT 'P1','P1-020','drh_user_assistant','p1'
    UNION ALL SELECT 'P1','P1-021','drh_user_form','p1'
    UNION ALL SELECT 'P1','P1-022','drh_user_service_record','p1'
    UNION ALL SELECT 'P1','P1-023','drh_voice_robot_callback_details','p1'
    UNION ALL SELECT 'P1','P1-024','drh_voice_robot_task_user','p1'
    UNION ALL SELECT 'P1','P1-025','drh_wechat_complaint_order','p1'
    UNION ALL SELECT 'P1','P1-026','order_book_reissue_detail','p1'
    UNION ALL SELECT 'P1','P1-027','drh_user_address','d003'
    UNION ALL SELECT 'P1','P1-028','drh_order_user_address','d003'
    UNION ALL SELECT 'P2','P2-001','drh_ad_count','p2'
    UNION ALL SELECT 'P2','P2-002','drh_ad_form_answer','p2'
    UNION ALL SELECT 'P2','P2-003','drh_applet_order','p2'
    UNION ALL SELECT 'P2','P2-004','drh_applet_small_user','p2'
    UNION ALL SELECT 'P2','P2-005','drh_goods_user_coupon','p2'
    UNION ALL SELECT 'P2','P2-006','drh_koc','p2'
    UNION ALL SELECT 'P2','P2-007','drh_order_refund_record','p2'
    UNION ALL SELECT 'P2','P2-008','drh_qwb_phone_info','p2'
    UNION ALL SELECT 'P2','P2-009','drh_short_message_operation','p2'
    UNION ALL SELECT 'P2','P2-010','drh_sms_trigger_user_callback','p2'
    UNION ALL SELECT 'P2','P2-011','drh_submit_time','p2'
    UNION ALL SELECT 'P2','P2-012','drh_xe_order','p2'
    UNION ALL SELECT 'P3','P3-001','drh_register_works','p3 candidate'
    UNION ALL SELECT 'P3','P3-002','drh_sms_deal','p3 candidate'
    UNION ALL SELECT 'P3','P3-003','drh_temp_phone','p3 candidate'
    UNION ALL SELECT 'P3','P3-004','drh_mall_order','p3 candidate; reciver_phone_*'
  ) et
  LEFT JOIN information_schema.TABLES t
    ON t.TABLE_SCHEMA = DATABASE()
   AND t.TABLE_NAME = et.table_name
  WHERE t.TABLE_NAME IS NULL

  UNION ALL

  SELECT ec.priority, ec.item_no, ec.table_name, 'COLUMN' AS object_type, ec.column_name AS object_name,
         'missing' AS status, ec.note
  FROM (
    SELECT 'P1' priority, 'P1-001' item_no, 'drh_h5_order' table_name, 'phone_mask' column_name, 'core' note
    UNION ALL SELECT 'P1','P1-001','drh_h5_order','phone_md5','core'
    UNION ALL SELECT 'P1','P1-001','drh_h5_order','phone_aes','core'
    UNION ALL SELECT 'P1','P1-002','drh_live_user','phone_mask','core'
    UNION ALL SELECT 'P1','P1-002','drh_live_user','phone_md5','core'
    UNION ALL SELECT 'P1','P1-002','drh_live_user','phone_aes','core'
    UNION ALL SELECT 'P1','P1-002','drh_live_user','app_phone_mask','core app_phone'
    UNION ALL SELECT 'P1','P1-002','drh_live_user','app_phone_md5','core app_phone'
    UNION ALL SELECT 'P1','P1-002','drh_live_user','app_phone_aes','core app_phone'
    UNION ALL SELECT 'P1','P1-003','drh_applet_user','phone_mask','core'
    UNION ALL SELECT 'P1','P1-003','drh_applet_user','phone_md5','core'
    UNION ALL SELECT 'P1','P1-003','drh_applet_user','phone_aes','core'
    UNION ALL SELECT 'P1','P1-004','drh_book_question_record','phone_mask','core'
    UNION ALL SELECT 'P1','P1-004','drh_book_question_record','phone_md5','core'
    UNION ALL SELECT 'P1','P1-004','drh_book_question_record','phone_aes','core'
    UNION ALL SELECT 'P1','P1-005','drh_external_book_question_record','phone_mask','core'
    UNION ALL SELECT 'P1','P1-005','drh_external_book_question_record','phone_md5','core'
    UNION ALL SELECT 'P1','P1-005','drh_external_book_question_record','phone_aes','core'
    UNION ALL SELECT 'P1','P1-006','drh_book_edit_address_compensation','phone_mask','core'
    UNION ALL SELECT 'P1','P1-006','drh_book_edit_address_compensation','phone_md5','core'
    UNION ALL SELECT 'P1','P1-006','drh_book_edit_address_compensation','phone_aes','core'
    UNION ALL SELECT 'P1','P1-007','drh_real_address_record','phone_mask','core'
    UNION ALL SELECT 'P1','P1-007','drh_real_address_record','phone_md5','core'
    UNION ALL SELECT 'P1','P1-007','drh_real_address_record','phone_aes','core'
    UNION ALL SELECT 'P1','P1-008','app_study_info','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-008','app_study_info','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-008','app_study_info','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-009','drh_app_white','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-009','drh_app_white','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-009','drh_app_white','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-010','drh_applet_black_phone','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-010','drh_applet_black_phone','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-010','drh_applet_black_phone','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-011','drh_applet_player','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-011','drh_applet_player','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-011','drh_applet_player','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-012','drh_gx_channel','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-012','drh_gx_channel','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-012','drh_gx_channel','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-013','drh_leads_noqw_send_msg_task_detail','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-013','drh_leads_noqw_send_msg_task_detail','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-013','drh_leads_noqw_send_msg_task_detail','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-014','drh_live_works_user','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-014','drh_live_works_user','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-014','drh_live_works_user','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-015','drh_renew_data','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-015','drh_renew_data','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-015','drh_renew_data','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-016','drh_sms_trigger_user','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-016','drh_sms_trigger_user','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-016','drh_sms_trigger_user','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-017','drh_specail_user','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-017','drh_specail_user','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-017','drh_specail_user','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-018','drh_sph_supplier_info','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-018','drh_sph_supplier_info','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-018','drh_sph_supplier_info','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-019','drh_user','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-019','drh_user','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-019','drh_user','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-020','drh_user_assistant','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-020','drh_user_assistant','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-020','drh_user_assistant','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-021','drh_user_form','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-021','drh_user_form','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-021','drh_user_form','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-022','drh_user_service_record','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-022','drh_user_service_record','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-022','drh_user_service_record','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-023','drh_voice_robot_callback_details','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-023','drh_voice_robot_callback_details','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-023','drh_voice_robot_callback_details','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-024','drh_voice_robot_task_user','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-024','drh_voice_robot_task_user','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-024','drh_voice_robot_task_user','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-025','drh_wechat_complaint_order','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-025','drh_wechat_complaint_order','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-025','drh_wechat_complaint_order','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-026','order_book_reissue_detail','phone_mask','p1'
    UNION ALL SELECT 'P1','P1-026','order_book_reissue_detail','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-026','order_book_reissue_detail','phone_aes','p1'
    UNION ALL SELECT 'P1','P1-027','drh_user_address','receiver_phone_mask','d003'
    UNION ALL SELECT 'P1','P1-027','drh_user_address','receiver_phone_md5','d003'
    UNION ALL SELECT 'P1','P1-027','drh_user_address','receiver_phone_aes','d003'
    UNION ALL SELECT 'P1','P1-028','drh_order_user_address','receiver_phone_mask','d003'
    UNION ALL SELECT 'P1','P1-028','drh_order_user_address','receiver_phone_md5','d003'
    UNION ALL SELECT 'P1','P1-028','drh_order_user_address','receiver_phone_aes','d003'
    UNION ALL SELECT 'P2','P2-001','drh_ad_count','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-001','drh_ad_count','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-001','drh_ad_count','phone_aes','p2'
    UNION ALL SELECT 'P2','P2-002','drh_ad_form_answer','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-002','drh_ad_form_answer','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-002','drh_ad_form_answer','phone_aes','p2'
    UNION ALL SELECT 'P2','P2-003','drh_applet_order','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-003','drh_applet_order','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-003','drh_applet_order','phone_aes','p2'
    UNION ALL SELECT 'P2','P2-004','drh_applet_small_user','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-004','drh_applet_small_user','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-004','drh_applet_small_user','phone_aes','p2'
    UNION ALL SELECT 'P2','P2-005','drh_goods_user_coupon','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-005','drh_goods_user_coupon','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-005','drh_goods_user_coupon','phone_aes','p2'
    UNION ALL SELECT 'P2','P2-006','drh_koc','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-006','drh_koc','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-006','drh_koc','phone_aes','p2'
    UNION ALL SELECT 'P2','P2-007','drh_order_refund_record','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-007','drh_order_refund_record','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-007','drh_order_refund_record','phone_aes','p2'
    UNION ALL SELECT 'P2','P2-008','drh_qwb_phone_info','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-008','drh_qwb_phone_info','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-008','drh_qwb_phone_info','phone_aes','p2'
    UNION ALL SELECT 'P2','P2-009','drh_short_message_operation','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-009','drh_short_message_operation','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-009','drh_short_message_operation','phone_aes','p2'
    UNION ALL SELECT 'P2','P2-010','drh_sms_trigger_user_callback','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-010','drh_sms_trigger_user_callback','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-010','drh_sms_trigger_user_callback','phone_aes','p2'
    UNION ALL SELECT 'P2','P2-011','drh_submit_time','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-011','drh_submit_time','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-011','drh_submit_time','phone_aes','p2'
    UNION ALL SELECT 'P2','P2-012','drh_xe_order','phone_mask','p2'
    UNION ALL SELECT 'P2','P2-012','drh_xe_order','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-012','drh_xe_order','phone_aes','p2'
    UNION ALL SELECT 'P3','P3-001','drh_register_works','phone_mask','p3 candidate'
    UNION ALL SELECT 'P3','P3-001','drh_register_works','phone_md5','p3 candidate'
    UNION ALL SELECT 'P3','P3-001','drh_register_works','phone_aes','p3 candidate'
    UNION ALL SELECT 'P3','P3-002','drh_sms_deal','phone_mask','p3 candidate'
    UNION ALL SELECT 'P3','P3-002','drh_sms_deal','phone_md5','p3 candidate'
    UNION ALL SELECT 'P3','P3-002','drh_sms_deal','phone_aes','p3 candidate'
    UNION ALL SELECT 'P3','P3-003','drh_temp_phone','phone_mask','p3 candidate'
    UNION ALL SELECT 'P3','P3-003','drh_temp_phone','phone_md5','p3 candidate'
    UNION ALL SELECT 'P3','P3-003','drh_temp_phone','phone_aes','p3 candidate'
    UNION ALL SELECT 'P3','P3-004','drh_mall_order','reciver_phone_mask','p3 candidate'
    UNION ALL SELECT 'P3','P3-004','drh_mall_order','reciver_phone_md5','p3 candidate'
    UNION ALL SELECT 'P3','P3-004','drh_mall_order','reciver_phone_aes','p3 candidate'
  ) ec
  JOIN information_schema.TABLES t
    ON t.TABLE_SCHEMA = DATABASE()
   AND t.TABLE_NAME = ec.table_name
  LEFT JOIN information_schema.COLUMNS c
    ON c.TABLE_SCHEMA = DATABASE()
   AND c.TABLE_NAME = ec.table_name
   AND c.COLUMN_NAME = ec.column_name
  WHERE c.COLUMN_NAME IS NULL

  UNION ALL

  SELECT ei.priority, ei.item_no, ei.table_name, 'INDEX' AS object_type, ei.index_name AS object_name,
         'missing' AS status, ei.note
  FROM (
    SELECT 'P1' priority, 'P1-001' item_no, 'drh_h5_order' table_name, 'idx_h5_order_phone_md5' index_name, 'phone_md5' column_name, 'core' note
    UNION ALL SELECT 'P1','P1-002','drh_live_user','idx_live_user_phone_md5','phone_md5','core'
    UNION ALL SELECT 'P1','P1-002','drh_live_user','idx_live_user_app_phone_md5','app_phone_md5','core app_phone'
    UNION ALL SELECT 'P1','P1-003','drh_applet_user','idx_applet_user_phone_md5','phone_md5','core'
    UNION ALL SELECT 'P1','P1-004','drh_book_question_record','idx_book_q_record_phone_md5','phone_md5','core'
    UNION ALL SELECT 'P1','P1-005','drh_external_book_question_record','idx_ext_book_q_record_phone_md5','phone_md5','core'
    UNION ALL SELECT 'P1','P1-006','drh_book_edit_address_compensation','idx_book_addr_comp_phone_md5','phone_md5','core'
    UNION ALL SELECT 'P1','P1-007','drh_real_address_record','idx_real_addr_phone_md5','phone_md5','core'
    UNION ALL SELECT 'P1','P1-008','app_study_info','idx_app_study_info_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-009','drh_app_white','idx_app_white_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-010','drh_applet_black_phone','idx_applet_black_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-011','drh_applet_player','idx_applet_player_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-012','drh_gx_channel','idx_gx_channel_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-013','drh_leads_noqw_send_msg_task_detail','idx_leads_noqw_msg_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-014','drh_live_works_user','idx_live_works_user_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-015','drh_renew_data','idx_renew_data_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-016','drh_sms_trigger_user','idx_sms_trigger_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-017','drh_specail_user','idx_specail_user_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-018','drh_sph_supplier_info','idx_sph_supplier_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-019','drh_user','idx_user_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-020','drh_user_assistant','idx_user_assistant_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-021','drh_user_form','idx_user_form_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-022','drh_user_service_record','idx_user_svc_record_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-023','drh_voice_robot_callback_details','idx_vr_callback_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-024','drh_voice_robot_task_user','idx_vr_task_user_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-025','drh_wechat_complaint_order','idx_wechat_complaint_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-026','order_book_reissue_detail','idx_book_reissue_phone_md5','phone_md5','p1'
    UNION ALL SELECT 'P1','P1-027','drh_user_address','idx_user_address_receiver_phone_md5','receiver_phone_md5','d003'
    UNION ALL SELECT 'P1','P1-028','drh_order_user_address','idx_order_user_address_receiver_phone_md5','receiver_phone_md5','d003'
    UNION ALL SELECT 'P2','P2-001','drh_ad_count','idx_ad_count_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-002','drh_ad_form_answer','idx_ad_form_answer_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-003','drh_applet_order','idx_applet_order_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-004','drh_applet_small_user','idx_applet_small_user_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-005','drh_goods_user_coupon','idx_goods_coupon_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-006','drh_koc','idx_koc_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-007','drh_order_refund_record','idx_order_refund_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-008','drh_qwb_phone_info','idx_qwb_phone_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-009','drh_short_message_operation','idx_short_msg_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-010','drh_sms_trigger_user_callback','idx_sms_trigger_cb_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-011','drh_submit_time','idx_submit_time_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P2','P2-012','drh_xe_order','idx_xe_order_phone_md5','phone_md5','p2'
    UNION ALL SELECT 'P3','P3-001','drh_register_works','idx_register_works_phone_md5','phone_md5','p3 candidate'
    UNION ALL SELECT 'P3','P3-002','drh_sms_deal','idx_sms_deal_phone_md5','phone_md5','p3 candidate'
    UNION ALL SELECT 'P3','P3-003','drh_temp_phone','idx_temp_phone_phone_md5','phone_md5','p3 candidate'
    UNION ALL SELECT 'P3','P3-004','drh_mall_order','idx_mall_order_reciver_phone_md5','reciver_phone_md5','p3 candidate'
  ) ei
  JOIN information_schema.TABLES t
    ON t.TABLE_SCHEMA = DATABASE()
   AND t.TABLE_NAME = ei.table_name
  LEFT JOIN information_schema.STATISTICS s
    ON s.TABLE_SCHEMA = DATABASE()
   AND s.TABLE_NAME = ei.table_name
   AND s.INDEX_NAME = ei.index_name
   AND s.COLUMN_NAME = ei.column_name
  WHERE s.INDEX_NAME IS NULL
) missing_objects
ORDER BY FIELD(priority, 'P1', 'P2', 'P3'), item_no, FIELD(object_type, 'TABLE', 'COLUMN', 'INDEX'), object_name;
