import json
from pathlib import Path


ROOT = Path(r"C:\workspace\ju-chat\specs\108-yaqi-piano-homework-config")
OUT = ROOT / "out"
SQL = ROOT / "sql"

TABLES = [
    (
        "drh_ai_config_homework_route",
        [
            "id",
            "day_num",
            "comment_index",
            "comment_match_type",
            "match_key",
            "match_value",
            "sku_id",
            "strategy_id",
            "enabled",
            "created_by",
            "updated_by",
            "created_at",
            "updated_at",
        ],
    ),
    (
        "drh_ai_config_homework_action",
        [
            "id",
            "strategy_id",
            "order_index",
            "action_type",
            "condition_key",
            "condition_value",
            "text_content",
            "material_url",
            "oss_url",
            "voice_duration_millis",
            "pdf_file_name",
            "pdf_file_size_bytes",
            "delay_millis",
            "enabled",
            "created_by",
            "updated_by",
            "created_at",
            "updated_at",
        ],
    ),
    (
        "drh_ai_config_homework_strategy",
        [
            "id",
            "strategy_name",
            "sku_id",
            "enabled",
            "remark",
            "created_by",
            "updated_by",
            "created_at",
            "updated_at",
        ],
    ),
]

INSERT_ORDER = [
    "drh_ai_config_homework_strategy",
    "drh_ai_config_homework_action",
    "drh_ai_config_homework_route",
]

DELETE_ORDER = [
    "drh_ai_config_homework_route",
    "drh_ai_config_homework_action",
    "drh_ai_config_homework_strategy",
]


def payload(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("truncated"):
        raise RuntimeError(f"refuse to generate SQL from truncated export: {path}")
    return data


def rows(prefix: str, table: str) -> list[dict]:
    suffix = table.replace("drh_ai_config_homework_", "")
    return payload(OUT / f"{prefix}-{suffix}.json")["rows"]


def sql_value(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    return "'" + text.replace("\\", "\\\\").replace("'", "''") + "'"


def insert_sql(table: str, columns: list[str], table_rows: list[dict]) -> str:
    if not table_rows:
        return ""
    quoted_columns = ", ".join(f"`{col}`" for col in columns)
    values = []
    for row in table_rows:
        values.append("(" + ", ".join(sql_value(row.get(col)) for col in columns) + ")")
    return f"INSERT INTO `{table}` ({quoted_columns}) VALUES\n" + ",\n".join(values) + ";\n"


def build(prefix: str, output_name: str) -> Path:
    table_map = {table: (columns, rows(prefix, table)) for table, columns in TABLES}
    lines = [
        "/* Generated by generate_homework_sync_sql.py. */",
        "/* Only homework config tables are touched. */",
        "",
    ]
    for table in DELETE_ORDER:
        lines.append(f"DELETE FROM `{table}`;")
    lines.append("")
    for table in INSERT_ORDER:
        columns, table_rows = table_map[table]
        lines.append(insert_sql(table, columns, table_rows))
    lines.append("SELECT 'strategy' AS table_name, COUNT(*) AS row_count FROM drh_ai_config_homework_strategy")
    lines.append("UNION ALL SELECT 'action', COUNT(*) FROM drh_ai_config_homework_action")
    lines.append("UNION ALL SELECT 'route', COUNT(*) FROM drh_ai_config_homework_route;")
    path = SQL / output_name
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main():
    sync_path = build("prod", "sync-test-homework-config-from-prod.sql")
    rollback_path = build("test-before-sync", "rollback-test-homework-config-before-sync.sql")
    summary = {
        "sync_sql": str(sync_path),
        "rollback_sql": str(rollback_path),
        "prod_counts": {
            table: len(rows("prod", table))
            for table, _ in TABLES
        },
        "test_backup_counts": {
            table: len(rows("test-before-sync", table))
            for table, _ in TABLES
        },
    }
    (OUT / "sync-sql-generation-summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
